version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - todo-app1
      - todo-app2

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todos
    ports:
      - "3306:3306"

  todo-app1:
    build: ./todo-app1
    container_name: todo-app1
    ports:
      - "3001:3000"

  todo-app2:
    build: ./todo-app2
    container_name: todo-app2
    ports:
      - "3002:3000"
